# Generated by Django 6.0.2 on 2026-04-09 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscriber',
            new_name='Newsletter',
        ),
    ]
